server:
  port: 8080
  servlet:
    context-path: /mail-project

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mail-project?createDatabaseIfNotExist=true"
    username: root
    password: root
  mail:
    host: localhost
    port: 25
    username: testuser@hvn.com
    password: 123456
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mail:
  imap:
    host: localhost
    port: 143
    ssl: false
    # Tài khoản mặc định (backward compatibility)
    default-username: testuser
    default-password: "123456"
    # Danh sách các tài khoản Dovecot
    accounts:
      - email: "testuser@hvn.com"
        username: "testuser"
        password: "123456"
        enabled: true
        description: "Tài khoản test chính"
      - email: "nhuan2002@hvn.com"
        username: "nhuan2002"
        password: "Nhuan2002@"
        enabled: true
        description: "Tài khoản nhuan2002"
      - email: "honhuan2002@hvn.com"
        username: "honhuan2002"
        password: "Nhuan2002@"
        enabled: true
        description: "Tài khoản honhuan2002"

# Logging Configuration
logging:
  level:
    com.hvn_proj_mail.mail.project: DEBUG
    org.springframework.mail: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

laoid:
  client-id: "660dfa27-5a95-4c88-8a55-abe1310bf579"
  client-secret: "df1699140bcb456eaa6d85d54c5fbd79"
  verify-url: "https://demo-sso.tinasoft.io/api/v1/third-party/verify"
  user-info-url: "https://demo-sso.tinasoft.io/api/v1/third-party/me"

jwt:
  secret: "c1ePB6X0x6EFoig/Si8Y6fF/pZBwOCPBwbpaXO5oZHz3t1jtKZCCqyfpH2XQOC1g"
  expirationMs: 86400000