version: '3.8'
services:
  postfix:
    build: ./postfix
    container_name: postfix
    hostname: mail.hvn.com
    ports:
      - "25:25"
      - "587:587"
    volumes:
      # - ./data/mail/testuser:/home/testuser
      - ./data:/data
      - ./postfix/vmailbox:/etc/postfix/vmailbox:ro
      - ./postfix/main.cf:/etc/postfix/main.cf
    networks:
      - mailnet

  dovecot:
    build: ./dovecot
    container_name: dovecot
    hostname: imap.hvn.com
    ports:
      - "143:143"
      - "993:993"
    volumes:
      - ./data:/data
    depends_on:
      - postfix
    networks:
      - mailnet

networks:
  mailnet:
    driver: bridge
